name: FreshRSS
version: "0.0.1-beta"
slug: freshrss
description: "FreshRSS dev version"
startup: application
boot: auto
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  80/tcp: 3000
ports_description:
  80/tcp: "Port for FreshRSS web interface, default is 3000."
map:
  - /config/freshrss:/config
options: {}
schema: {}
url: "https://github.com/Ondra9071/hassio-addons/"
panel_icon: "mdi:broadcast"
ingress: false
advanced: false